### PR TITLE
Update DefaultCondition in init() function.

### PR DESCRIPTION
**Pull request by markus-oberhumer**
This is an oversight in git commit ef4e261f1f0f2198dbea63dfc6639910969ef297.

### CODE REVIEW

**Comment by mattn** [comment]
This break compatibility

**Comment by mattn** [comment]
FYI, Your commit change the type of DefaultCondition.

**Comment by markus-oberhumer** [comment]
Well, after git commit ef4e261f1f0f2198dbea63dfc6639910969ef297 the value of DefaultCondition.EastAsianWidth is always false.

```
package main
  
import "fmt"

type Condition struct {
        EastAsianWidth bool
}

var (
        // EastAsianWidth will be set true if the current locale is CJK
        EastAsianWidth bool

        // DefaultCondition is a condition in current locale
        DefaultCondition = &Condition{EastAsianWidth}
)

func init() {
        EastAsianWidth = true // ASSUME true
}

func main() {
        fmt.Printf("%v %v\n", EastAsianWidth, DefaultCondition.EastAsianWidth)
}
```

**Comment by markus-oberhumer** [comment]
> FYI, Your commit change the type of DefaultCondition.

Yes, just noticed that as well. But why is DefaultCondition a pointer in the first place?

**Comment by markus-oberhumer** [comment]
Ok, I've updated the pull request so that the type of DefaultCondition is unchanged.

Please feel free to close this request if you think the current version is correct. Thanks!

**Comment by mattn** [comment]
Thank you.

**Pull request merged**
