### PR TITLE
EastAsianWidth.txt, use the record with "F"(FULLWIDTH) field as same as "W"

### PR DESCRIPTION
**Pull request by zetamatta**
For the issue [possible regression ? · Issue #32 · mattn/go-runewidth](https://github.com/mattn/go-runewidth/issues/32).

On the script/generate.go reading https://unicode.org/Public/12.1.0/ucd/EastAsianWidth.txt , the record which has "F"(FullWidth) field is not used as same as "W".
So, I tried to fix to support and update checksums (Is it to remind `go generate` ?) 

Would you like to merge if there are no problems ?

### CODE REVIEW

**Comment by mattn** [comment]
Thank you.

**Comment by MichaelMure** [comment]
Could you tag a release with this fix ? My problem is that with go 1.10 (before go module), the last release is downloaded which is the broken one at the moment.

**Comment by mattn** [comment]
Tagged v0.0.6

**Comment by MichaelMure** [comment]
Thanks :)

**Pull request merged**
