### PR TITLE
Optimize speed

### PR DESCRIPTION
**Pull request by markus-oberhumer**

### CODE REVIEW

**Comment by markus-oberhumer** [comment]
Just FYI, a follow-up commit will optimize ("compact") the neutral table.

**Comment by mattn** [comment]
Thanks. One thing, please remove Makefile since I hope that go-runewidth works on any system that doesn't install make command.

**Comment by markus-oberhumer** [comment]
Hi, I've created a new version of this pull request that is rebased to current master and removes the Makefile.

JFYI, I usually like simple Makefiles because these give you a quick clue how to build or test a package without having to read the docs...

**Comment by mattn** [comment]
Yes, I understand. Thank you. Just I'm thinking if we add Makefile, someone may think go-runewidth require make command for docker image.

**Comment by mattn** [comment]
Thanks.

**Pull request merged**
