### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by markus-oberhumer**
Assorted minor cleanups. NFC.

### CODE REVIEW

**Comment by mattn** [comment]
Thank you. Could you please insert this into `.travis.yml` ?

```
 script:
    - go generate
```

**Comment by markus-oberhumer** [comment]
Are you sure that re-generating the files each time in Travis is a good idea?

I think this should be handled manually.

**Comment by mattn** [comment]
Adding `git diff` also might be useful.

**Comment by markus-oberhumer** [comment]
Well, then please merge this and change .travis.yml to your liking.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
